name: Visual DNS Homework
on: [workflow_dispatch]

jobs:
  visual-dns-setup:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Install GUI and tools
      run: |
        sudo apt-get update
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
          xvfb xfce4 xfce4-terminal \
          ffmpeg xdotool vim-tiny \
          dnsmasq gnome-icon-theme

    - name: Start desktop environment
      run: |
        # Start Xvfb with screen
        Xvfb :99 -screen 0 1280x720x24 +extension RANDR &
        export DISPLAY=:99
        
        # Start XFCE with visible panel
        startxfce4 > /dev/null 2>&1 &
        sleep 8  # Give time for desktop to load

        # Set basic theme
        xfconf-query -c xsettings -p /Net/ThemeName -s "Adwaita"
        xfconf-query -c xsettings -p /Net/IconThemeName -s "Adwaita"

        # Start recording with higher quality
        ffmpeg -y -f x11grab -video_size 1280x720 -framerate 24 -i :99 -c:v libx264 -preset fast output.mp4 &

    - name: Simulate human interaction
      run: |
        export DISPLAY=:99
        
        # Show mouse movements
        xdotool mousemove 500 500  # Center screen
        sleep 1
        
        # Open terminal with right-click menu
        xdotool mousemove 50 700 click 3  # Open panel menu
        sleep 1
        xdotool key Down Down Down Return  # Select terminal
        sleep 2

        # Type commands with human-like delays
        function typecmd() {
          xdotool type --delay 120 "$@"
          xdotool key Return
          sleep 1.5
        }

        typecmd "sudo nano /etc/dnsmasq.conf"
        typecmd "echo -e 'address=/ahmadi.me/1.2.3.4\naddress=/blog.ahmadi.me/2.2.2.2\naddress=/dev.ahmadi.me/4.4.4.4' | sudo tee -a /etc/dnsmasq.conf"
        typecmd "sudo systemctl restart dnsmasq"
        typecmd "nslookup ahmadi.me"
        typecmd "nslookup blog.ahmadi.me"
        typecmd "nslookup dev.ahmadi.me"
        typecmd "exit"

    - name: Finalize recording
      run: |
        pkill -INT ffmpeg
        sleep 5
        convert -size 1280x720 xc:black -pointsize 40 -fill white -annotate +100+360 "DNS Configuration Complete" output-final.mp4
        ffmpeg -i output.mp4 -i output-final.mp4 -filter_complex concat=n=2:v=1:a=0 final.mp4 -y

    - name: Upload proof
      uses: actions/upload-artifact@v4
      with:
        name: dns-gui-proof
        path: final.mp4
