name: DNS Homework Automation
on: [workflow_dispatch]

jobs:
  automate-dns-setup:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
    - name: Set up Xvfb and recording
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb ffmpeg dnsmasq bind9-utils

    - name: Start virtual display
      run: Xvfb :99 -screen 0 1280x720x24 &
      env:
        DISPLAY: :99

    - name: Start screen recording
      run: ffmpeg -y -f x11grab -video_size 1280x720 -framerate 15 -i :99 -codec:v libx264rgb output.mp4 &
      env:
        DISPLAY: :99

    - name: Configure DNS
      run: |
        # Configure dnsmasq with external DNS fallback
        echo "listen-address=127.0.0.1" | sudo tee -a /etc/dnsmasq.conf
        echo "server=8.8.8.8" | sudo tee -a /etc/dnsmasq.conf  # Google DNS fallback
        echo "no-resolv" | sudo tee -a /etc/dnsmasq.conf
        echo "local=/ahmadi.me/" | sudo tee -a /etc/dnsmasq.conf
        echo "address=/ahmadi.me/1.2.3.4" | sudo tee -a /etc/dnsmasq.conf
        echo "address=/blog.ahmadi.me/2.2.2.2" | sudo tee -a /etc/dnsmasq.conf
        echo "address=/dev.ahmadi.me/4.4.4.4" | sudo tee -a /etc/dnsmasq.conf

        # Handle system DNS carefully
        sudo systemctl stop systemd-resolved || true
        echo "nameserver 127.0.0.1" | sudo tee /etc/resolv.conf
        echo "nameserver 8.8.8.8" | sudo tee -a /etc/resolv.conf  # Dual DNS config
        sudo chattr +i /etc/resolv.conf

        # Restart service
        sudo systemctl restart dnsmasq
        sleep 2

        # Verify external DNS resolution
        nslookup github.com
        nslookup actions.githubusercontent.com

        # Test homework records
        nslookup ahmadi.me 127.0.0.1
        nslookup blog.ahmadi.me 127.0.0.1
        nslookup dev.ahmadi.me 127.0.0.1

    - name: Stop recording and save
      run: |
        pkill -INT ffmpeg
        sleep 5
        pkill Xvfb

    - name: Upload recording with retries
      uses: actions/upload-artifact@v4
      with:
        name: dns-setup-recording
        path: output.mp4
        retention-days: 1
      timeout-minutes: 5  # Give extra time for upload
