name: Visual DNS Homework
on: [workflow_dispatch]

jobs:
  visual-dns-setup:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
    - name: Install GUI and tools
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          xvfb xfce4 x11-apps \
          ffmpeg xdotool \
          gnome-terminal dnsmasq

    - name: Start desktop and recording
      run: |
        # Start virtual display
        Xvfb :99 -screen 0 1280x720x24 +extension RANDR &
        export DISPLAY=:99

        # Start XFCE desktop
        startxfce4 &
        sleep 5

        # Start recording
        ffmpeg -y -f x11grab -video_size 1280x720 -framerate 15 -i :99 -codec:v libx264rgb output.mp4 &

    - name: Simulate human interaction
      run: |
        export DISPLAY=:99
        
        # Open terminal with mouse-like behavior
        xdotool mousemove 100 100 click 1
        xdotool key ctrl+alt+t
        sleep 2

        # Type commands slowly
        xdotool type --delay 100 "sudo -i"
        xdotool key Return
        sleep 1
        
        xdotool type --delay 50 "apt-get install -y dnsmasq"
        xdotool key Return
        sleep 3

        xdotool type --delay 100 "echo 'address=/ahmadi.me/1.2.3.4' >> /etc/dnsmasq.conf"
        xdotool key Return
        sleep 1
        
        xdotool type --delay 100 "echo 'address=/blog.ahmadi.me/2.2.2.2' >> /etc/dnsmasq.conf"
        xdotool key Return
        sleep 1
        
        xdotool type --delay 100 "echo 'address=/dev.ahmadi.me/4.4.4.4' >> /etc/dnsmasq.conf"
        xdotool key Return
        sleep 1

        xdotool type --delay 100 "systemctl restart dnsmasq"
        xdotool key Return
        sleep 2

        xdotool type --delay 100 "nslookup ahmadi.me"
        xdotool key Return
        sleep 2
        
        xdotool type --delay 100 "nslookup blog.ahmadi.me"
        xdotool key Return
        sleep 2

        xdotool type --delay 100 "nslookup dev.ahmadi.me"
        xdotool key Return
        sleep 3

    - name: Finalize and upload
      run: |
        pkill -INT ffmpeg
        sleep 5
      always(): true

    - name: Upload recording
      uses: actions/upload-artifact@v4
      with:
        name: gui-dns-proof
        path: output.mp4
